version: "3.7"

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env
    command: gunicorn bookie.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    volumes:
      - mysql_data:/var/lib/mysql/data/
    env_file:
      - ./mysql/.env
  react:
    build:
      context: ./bookie_ui
      dockerfile: Dockerfile
      args:
        - API_SERVER=${ENV_API_SERVER}
    volumes:
      - react_static_volume:/usr/src/app/ui/build/static
    expose:
      - 3000
    env_file:
      - .env
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - react_static_volume:/usr/src/app/ui/react_files/static
    ports:
      - 80:80
    depends_on:
      - react

volumes:
  mysql_data:
  django_static_volume:
  react_static_volume: