apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookie_service
  name: bookie-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: bookie_service
status:
  loadBalancer: {}