apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookie
  name: bookie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookie
  strategy: {}
  template:
    metadata:
      labels:
        app: bookie
    spec:
      containers:
      - image: shrey27tri01/bookie:v0
        name: bookie
        resources: {}
        env:
          - name: DB_NAME
            value: "bookie"
          - name: MYSQL_HOST
            value: "db-service"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_PASSWORD
            value: "Tripathi"
          - name: FRONTEND
            value: "ui-service"
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: /var/log/
            name: bookie
        # command: ["/bin/sh", "-c", "echo \"127.0.0.1 db-service\" >> /etc/hosts && gunicorn bookie.wsgi --bind 0.0.0.0:8000"]
        # command: ["/bin/sh", "-c", "echo \"127.0.0.1 db-service\" >> /etc/hosts"]
        # args:
          # - apt-get update;
          #   apt-get -y install vim;
          #   echo $PATH;
          #   pip freeze;
          #   python manage.py makemigrations;
          #   python manage.py migrate;
          #   # gunicorn --bind 0.0.0.0:8000 --workers 3 bookie.wsgi:application
      volumes:
        - name: bookie
          hostPath:
            path: /var/log/
status: {}
