apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  #env variables for the mysql component
  MYSQL_USER: root
  MYSQL_DB: bookie

  #env variables for the backend component
  DJANGO_ENV: development
  DEBUG: "1"
  SECRET_KEY: secretsecretsecretsecretsecret
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: admin
  DJANGO_ADMIN_EMAIL: "shreytripathi27@gmail.com"
  DJANGO_ADMIN_FIRST_NAME: admin

  DATABASE: mysql
  DB_ENGINE: "django.db.backends.mysql"
  DB_DATABASE: bookie
  DB_USER: root
  DB_HOST: mysql-cluster-ip-service
  DB_PORT: "3306"