apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: bookie_db
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
status:
  loadBalancer: {}
