name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  VM_IP_ADDRESS: "40.76.242.180"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/bookie:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./bookie_ui
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/bookie_ui:latest

      - name: SSH into Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_IP_ADDRESS }}
          username: azureuser
          key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kubernetes/backend.yaml
          kubectl apply -f ./kubernetes/frontend.yaml